### ISSUE TITLE
Remove hard coded SQL statementr from the code

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/web-reporting#25]
Last summer, it was agreed that there should not be inline SQL into the application in except one report page. Today I found out that the authentication method is made by an inline SQL statement in the application and not in a stored procedure. This is a very bad programming practice and could bring security vulnerabilities (Ex: a user to connect without a password).

**Comment by LaurentGoderre** [comment]
The file in question is WarMembershipProvider.vb

**Comment by LaurentGoderre** [comment]
Correction the file is WarMembershipProvider.cs

**Comment by dfait-webstandards** [comment]
The report page mentioned in original issue text refers to the manage assessment page. This inline sql statement cannot be removed until we move to .Net4.0
