### ISSUE TITLE
Lock the user for 10 minutes after 5 failed login attempts

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/web-reporting#3]

**Comment by ccantesa** [comment]
Fail - User is locked out for 10 mins, given a nice error message telling them that, but then can't log back in , see issue #6

**Comment by LaurentGoderre** [comment]
@ccantesa does this mean this works as well?

**Comment by ccantesa** [comment]
Verifying, will update once known

**Comment by ccantesa** [comment]
Re-tested and user is able to log into application
