### ISSUE TITLE
Cannot delete record for ADM Led Organizations or Websites

### ISSUE THREAD

**Issue by irwink** [wet-boew/web-reporting#35]
Cannot delete record for ADM Led Organizations if they are not needed or added in error.
http://publiservice.tbs-sct.gc.ca/ws-nw/wr-rw/administration/led-organization.aspx?lang=eng

Cannot delete record for Websites  if they are not needed or added in error.
http://publiservice.tbs-sct.gc.ca/ws-nw/wr-rw/administration/inventory-inventaire.aspx?lang=eng

Similar to Issue# 34 https://github.com/wet-boew/web-reporting/issues/34
Add a delete assessment team option

**Comment by LaurentGoderre** [comment]
@irwink I will close this because I'm already adding issues for those with specs.

**Comment by irwink** [comment]
What is the issue number for the one you are adding ? I can't track the progress of my issue if I don't have the issue number.

**Comment by LaurentGoderre** [comment]
See issue #43 & #44
