### ISSUE TITLE
Add a delete ADM organization option

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/web-reporting#43]
![delete_adm_org](https://f.cloud.github.com/assets/1090826/22903/33bfd0a4-4a19-11e2-8cef-ac56457d3f20.JPG)
1. In the 'Manage assessment team' add two column that shows the number of websites associated to each ADM organizations (Business Owner and Web Publishing Owner).
   - Business Owner for number of Websites (English)
   - Web Publishing/Development Owner for number of Websites (English)
   - Propriétaire opérationnel pour nombre de sites Web (French)
   - Propriétaire fonctionnel pour nombre de sites Web (French)
2. Add a link called 'Delete' in English and 'Supprimer' in French after the edit button for organizations that are not owner of any sites (either Business or Development/Publishing)
3. Add a stored procedure to delete an assessment team. The stored procedure MUST check that the organization is not the owner for any site. If the organization is the business owner of one or more sites return an error code (1). If the organization is the web publishing owner of one or more site return another error code (2). Otherwise, return 0.
4. In the application, when thew delete button is clicked a confirmation is displayed:
   - 'Are you sure you want to delete this ADM Led Organization?' (English)
   - 'Êtes-vous certain de vouloir supprimer cette organisations dirigées par un SMA?' (French)
5. if the user selects yes, the store procedure is executed and the application returns to the 'Manage ADM Led Organizations ' page. 

If the error code 1 is returned from the stored procedure, show the following error message:
- 'The [organization name] ADM Led Organization could not be deleted because it is the business owner of some websites' (English)
-  'L'organisations dirigées par un SMA [organization name] n'a pas pu être supprimé parce l'organization est propriétaire opérationnel de sites Web' (French)

If the error code 2 is returned from the stored procedure, show the following error message:
- 'The [organization name] organization could not be deleted because it is the publishing/development owner of some websites' (English)
-  'L'organisations dirigées par un SMA [organization name] n'a pas pu être supprimé parce l'organization est propriétaire fonctionnel de sites Web' (French)

If no error is returned display the following message:
- 'The [organization name] ADM Led Organization has been deleted' (English)
- L'organisations dirigées par un SMA [organization name] a été supprimé' (French)

**Comment by FarazAliKhan** [comment]
fixed

**Comment by dzhaotbs** [comment]
Tested and passed
