### ISSUE TITLE
Add a delete Website option

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/web-reporting#44]
1. In the 'Manage Websites' page add a column that list the number of assigned assessments for each site
   - Number of assigned assessments' (English)
     *Nombre d'évaluation assignés (French)
2. Add a link called 'Delete' in English and 'Supprimer' in French after the edit button for websites that do not have any assigned assessments
3. Add a stored procedure to delete a website. The stored procedure MUST check that the site does not have any assigned web page. If the site has pages, return an error code(1). Otherwise, return 0.
4. In the application, when the delete button is clicked a confirmation is displayed:
   - 'Are you sure you want to delete this Website?' (English)
   - 'Êtes-vous certain de vouloir supprimer ce site Web?' (French)
5. If the user selects yes, the store procedure is executed and the application returns to the 'Manage Websites ' page. 

If an error is returned from the stored procedure, show the following error message:
- 'The [Website name] website could not be deleted because it has associated assessments' (English)
- 'Le site Web [Website name] n'a pas pu être supprimé parce que des évaluations lui sont associés' (French)

If no error is returned display the following message:
- 'The [Website name] Website has been deleted' (English)
- 'Le site Web [Website name] a été supprimé' (French)

**Comment by dzhaotbs** [comment]
Tested and passed
