### ISSUE TITLE
Add webpage validation changes

### ISSUE THREAD

**Issue by dfait-webstandards** [wet-boew/web-reporting#54]
Can you please remove the following validation from the Assign Webpage page:
- Remove validation requiring an extention on the end of the URL (For example, I should be able to enter http://voyage.gc.ca/economics in the URL field)
- Remove validation that doesn't allow multiple occurences of the same URL (if this exists)

**Comment by FarazAliKhan** [comment]
fixed

**Comment by dzhaotbs** [comment]
Tested and passed.
