### ISSUE TITLE
Redirect the user to the login screen when the session timesout

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/web-reporting#6]
There currently is loss of data occuring when the session timesout but the user is still allowed to input data.

**Comment by ccantesa** [comment]
Fail - Redirects to login page but when you login you get a blank screen. We get this URL: http://staging.publiservice.tbs-sct.gc.ca/ws-nw/wr-rw/GenericErrorPage.htm?aspxerrorpath=/ws-nw/wr-rw/administration/institution.aspx.

When I open a new IE window and login, I get a blank page, this URL: http://staging.publiservice.tbs-sct.gc.ca/ws-nw/wr-rw/GenericErrorPage.htm?aspxerrorpath=/ws-nw/wr-rw/administration/institution.aspx

**Comment by LaurentGoderre** [comment]
@ccantesa can you please try this again?

**Comment by ccantesa** [comment]
Re-tested - Application redirects me to the login screen when the session timesout (30 minutes)

**Comment by LaurentGoderre** [comment]
The timeout redirect doesn't happen all the time.

**Comment by dfait-webstandards** [comment]
@LaurentGoderre It is working perfectly on other environments. Please investigate your environment and report back.

**Comment by dzhaotbs** [comment]
Tested and passed.

**Comment by LaurentGoderre** [comment]
Not quite but it's a configuration issue.

@dfait-webstandards please set the session timeout and authentication timeout to 55 minutes. Also change the timeout warning to 50 minutes.

Thanks
